"use client";

import { Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { ReportData } from "./types";
import { ExecutiveSummarySection } from "./report-sections/executive-summary";
import { SiteHealthSection } from "./report-sections/site-health-section";
import { TechnicalIssuesSection } from "./report-sections/technical-issues-section";
import { CwvSection } from "./report-sections/cwv-section";
import { AiSearchSection } from "./report-sections/ai-search-section";
import { KeywordRankingsSection } from "./report-sections/keyword-rankings-section";
import { GscPerformanceSection } from "./report-sections/gsc-performance-section";
import { RecommendationsSection } from "./report-sections/recommendations-section";

interface Props {
  reportData: ReportData;
  showPrintButton?: boolean;
}

const DATE_RANGE_LABELS: Record<string, string> = {
  "30d": "Last 30 days",
  "90d": "Last 90 days",
  "180d": "Last 6 months",
};

export function ReportPreview({ reportData, showPrintButton = true }: Props) {
  const { sections } = reportData;
  const has = (s: string) => sections.includes(s);

  const generatedDate = new Date(reportData.generatedAt).toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });

  const healthScore = reportData.siteHealth?.score ?? null;
  const scoreColor =
    healthScore == null ? "#9CA3AF" :
    healthScore >= 80 ? "#00C48C" :
    healthScore >= 50 ? "#FF8C00" : "#F34E4E";

  return (
    <div className="report-content">
      {/* Print action bar — hidden in print */}
      {showPrintButton && (
        <div className="print-hide flex justify-end mb-4">
          <Button variant="outline" size="sm" onClick={() => window.print()} className="gap-2">
            <Printer className="h-4 w-4" />
            Download PDF
          </Button>
        </div>
      )}

      {/* Report content — printed */}
      <div id="report-content" className="space-y-4">
        {/* ── Header ── */}
        <div className="report-section rounded-lg border bg-white p-6">
          <div className="flex items-start justify-between">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <span className="text-xs font-semibold uppercase tracking-widest text-primary">VisibilityOS</span>
                <span className="text-xs text-muted-foreground">· SEO Report</span>
              </div>
              <h1 className="text-2xl font-bold">{reportData.title}</h1>
              <p className="text-muted-foreground mt-1">
                {reportData.project.name} · {reportData.project.domain}
              </p>
              <p className="text-sm text-muted-foreground mt-0.5">
                {DATE_RANGE_LABELS[reportData.dateRange] ?? reportData.dateRange} · Generated {generatedDate}
              </p>
            </div>
            {healthScore != null && (
              <div className="text-center shrink-0">
                <p className="text-4xl font-bold tabular-nums" style={{ color: scoreColor }}>{Math.round(healthScore)}</p>
                <p className="text-xs text-muted-foreground">/100 health score</p>
              </div>
            )}
          </div>
        </div>

        {/* ── Sections ── */}
        {has("executive_summary") && <ExecutiveSummarySection data={reportData.executiveSummary} />}
        {has("site_health") && <SiteHealthSection data={reportData.siteHealth} />}
        {has("technical_issues") && <TechnicalIssuesSection data={reportData.technicalIssues} />}
        {has("cwv") && <CwvSection data={reportData.cwv} />}
        {has("ai_search") && <AiSearchSection data={reportData.aiSearch} />}
        {has("keywords") && <KeywordRankingsSection data={reportData.keywords} />}
        {has("gsc") && <GscPerformanceSection data={reportData.gsc} />}
        {has("recommendations") && <RecommendationsSection data={reportData.recommendations} />}

        {/* ── Footer ── */}
        <div className="text-center py-4 text-xs text-muted-foreground border-t">
          Generated by VisibilityOS · {generatedDate} · {reportData.project.domain}
        </div>
      </div>
    </div>
  );
}
